---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push: {}
  pull_request: {}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          cache: true
          cache_key: 'mise'

      - name: Run actionlint
        run: mise exec -- actionlint

  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          cache: true
          cache_key: 'mise'

      - name: Run renovate-config-validator
        run: mise exec -- renovate-config-validator default.json5
