---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push: {}
  pull_request: {}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          cache: true
          cache_key: 'mise'

      - name: Run actionlint
        run: mise exec -- actionlint

  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          cache: true
          cache_key: 'mise'

      - name: Run renovate-config-validator
        run: mise exec -- renovate-config-validator default.json5
